2025-05-17 07:12:36.301 WARNING (MainThread) [homeassistant.bootstrap] Skipping pip installation of required modules. This may cause issues
2025-05-17 07:12:36.304 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration uk_bin_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-05-17 07:12:36.636 WARNING (MainThread) [aiohttp_fast_zlib] zlib_ng and isal are not available, falling back to zlib, performance will be degraded.
2025-05-17 07:12:36.718 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.08 seconds
2025-05-17 07:12:36.718 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.08 seconds
2025-05-17 07:12:36.718 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.08 seconds
2025-05-17 07:12:36.718 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2025-05-17 07:12:36.718 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.00 seconds
2025-05-17 07:12:36.719 INFO (MainThread) [homeassistant.setup] Setting up network
2025-05-17 07:12:36.719 INFO (MainThread) [homeassistant.setup] Setup of domain network took 0.00 seconds
2025-05-17 07:12:36.719 INFO (MainThread) [homeassistant.bootstrap] Setting up stage frontend: {'frontend'} | set()
Dependencies: {'diagnostics', 'file_upload', 'search', 'lovelace', 'api', 'repairs', 'device_automation', 'onboarding', 'config', 'auth'} | {'http', 'websocket_api', 'system_log'}
2025-05-17 07:12:36.719 INFO (MainThread) [homeassistant.setup] Setting up diagnostics
2025-05-17 07:12:36.720 INFO (MainThread) [homeassistant.setup] Setup of domain diagnostics took 0.00 seconds
2025-05-17 07:12:36.720 INFO (MainThread) [homeassistant.setup] Setting up api
2025-05-17 07:12:36.721 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.00 seconds
2025-05-17 07:12:36.721 INFO (MainThread) [homeassistant.setup] Setting up auth
2025-05-17 07:12:36.721 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.00 seconds
2025-05-17 07:12:36.721 INFO (MainThread) [homeassistant.setup] Setting up config
2025-05-17 07:12:36.722 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.00 seconds
2025-05-17 07:12:36.722 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2025-05-17 07:12:36.722 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.00 seconds
2025-05-17 07:12:36.722 INFO (MainThread) [homeassistant.setup] Setting up file_upload
2025-05-17 07:12:36.722 INFO (MainThread) [homeassistant.setup] Setup of domain file_upload took 0.00 seconds
2025-05-17 07:12:36.722 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2025-05-17 07:12:36.722 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.00 seconds
2025-05-17 07:12:36.722 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2025-05-17 07:12:36.723 INFO (MainThread) [homeassistant.setup] Setting up repairs
2025-05-17 07:12:36.723 INFO (MainThread) [homeassistant.setup] Setup of domain repairs took 0.00 seconds
2025-05-17 07:12:36.723 INFO (MainThread) [homeassistant.setup] Setting up search
2025-05-17 07:12:36.723 INFO (MainThread) [homeassistant.setup] Setup of domain search took 0.00 seconds
2025-05-17 07:12:36.723 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.00 seconds
2025-05-17 07:12:36.724 INFO (MainThread) [homeassistant.setup] Setting up frontend
2025-05-17 07:12:36.725 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.00 seconds
2025-05-17 07:12:36.726 INFO (MainThread) [homeassistant.bootstrap] Setting up stage recorder: {'recorder'} | set()
Dependencies: set() | set()
2025-05-17 07:12:36.726 INFO (MainThread) [homeassistant.setup] Setting up recorder
2025-05-17 07:12:36.727 INFO (MainThread) [homeassistant.components.http] Now listening on port 8123
2025-05-17 07:12:36.728 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.00 seconds
2025-05-17 07:12:36.728 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //Users/davidamor/GitHub/homeassistant-debug/config/home-assistant_v2.db was shutdown cleanly
2025-05-17 07:12:36.746 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=375 from 2025-05-16 20:43:10.062294)
2025-05-17 07:12:36.752 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 0.03 seconds
2025-05-17 07:12:36.752 INFO (MainThread) [homeassistant.bootstrap] Nothing to set up in stage debugger: {'debugpy'}
2025-05-17 07:12:36.752 INFO (MainThread) [homeassistant.bootstrap] Setting up stage zeroconf: {'zeroconf'} | set()
Dependencies: set() | {'api', 'network', 'websocket_api', 'http'}
2025-05-17 07:12:36.752 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2025-05-17 07:12:36.754 INFO (MainThread) [homeassistant.components.zeroconf] Starting Zeroconf broadcast
2025-05-17 07:12:36.754 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 0.00 seconds
2025-05-17 07:12:36.754 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 1: {'ssdp', 'bluetooth', 'cloud', 'usb', 'dhcp'} | set()
Dependencies: {'webhook', 'backup', 'wake_word', 'tts', 'conversation', 'assist_pipeline', 'intent', 'ffmpeg', 'stt'} | {'network', 'repairs', 'http', 'auth', 'websocket_api'}
2025-05-17 07:12:36.754 INFO (MainThread) [homeassistant.setup] Setting up webhook
2025-05-17 07:12:36.755 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.00 seconds
2025-05-17 07:12:36.755 INFO (MainThread) [homeassistant.setup] Setting up backup
2025-05-17 07:12:36.756 INFO (MainThread) [homeassistant.setup] Setup of domain backup took 0.00 seconds
2025-05-17 07:12:36.759 INFO (MainThread) [homeassistant.setup] Setting up wake_word
2025-05-17 07:12:36.759 INFO (MainThread) [homeassistant.setup] Setup of domain wake_word took 0.00 seconds
2025-05-17 07:12:36.761 INFO (MainThread) [homeassistant.setup] Setting up ffmpeg
2025-05-17 07:12:36.767 ERROR (MainThread) [haffmpeg.core] FFmpeg fails [Errno 2] No such file or directory: 'ffmpeg'
Traceback (most recent call last):
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/haffmpeg/core.py", line 130, in open
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/subprocess.py", line 224, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        stderr=stderr, **kwds)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 1788, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        protocol, popen_args, False, stdin, stdout, stderr,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        bufsize, **kwargs)
        ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/unix_events.py", line 213, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
                                    stdin, stdout, stderr, bufsize,
                                    waiter=waiter, extra=extra,
                                    **kwargs)
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_subprocess.py", line 39, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                stderr=stderr, bufsize=bufsize, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/unix_events.py", line 855, in _start
    self._proc = subprocess.Popen(
                 ~~~~~~~~~~~~~~~~^
        args, shell=shell, stdin=stdin, stdout=stdout, stderr=stderr,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        universal_newlines=False, bufsize=bufsize, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 1969, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
2025-05-17 07:12:36.780 WARNING (MainThread) [haffmpeg.tools] Error starting FFmpeg.
2025-05-17 07:12:36.780 INFO (MainThread) [homeassistant.setup] Setup of domain ffmpeg took 0.02 seconds
2025-05-17 07:12:36.780 INFO (MainThread) [homeassistant.setup] Setting up intent
2025-05-17 07:12:36.781 INFO (MainThread) [homeassistant.setup] Setup of domain intent took 0.00 seconds
2025-05-17 07:12:36.784 INFO (MainThread) [homeassistant.setup] Setting up stt
2025-05-17 07:12:36.785 INFO (MainThread) [homeassistant.setup] Setup of domain stt took 0.00 seconds
2025-05-17 07:12:36.809 INFO (MainThread) [homeassistant.setup] Setting up ssdp
2025-05-17 07:12:36.815 INFO (MainThread) [homeassistant.setup] Setup of domain ssdp took 0.01 seconds
2025-05-17 07:12:36.820 INFO (MainThread) [homeassistant.setup] Setting up usb
2025-05-17 07:12:36.820 INFO (MainThread) [homeassistant.components.usb] Falling back to periodic filesystem polling for development, aiousbwatcher is not available on this system: Inotify not available on this platform
2025-05-17 07:12:36.820 INFO (MainThread) [homeassistant.setup] Setup of domain usb took 0.00 seconds
2025-05-17 07:12:36.876 INFO (MainThread) [homeassistant.setup] Setting up dhcp
2025-05-17 07:12:36.877 INFO (MainThread) [homeassistant.setup] Setup of domain dhcp took 0.00 seconds
2025-05-17 07:12:36.897 INFO (MainThread) [homeassistant.setup] Setting up tts
2025-05-17 07:12:36.898 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 0.00 seconds
2025-05-17 07:12:36.933 INFO (MainThread) [homeassistant.setup] Setting up conversation
2025-05-17 07:12:36.951 INFO (MainThread) [homeassistant.setup] Setup of domain conversation took 0.02 seconds
2025-05-17 07:12:36.952 INFO (MainThread) [homeassistant.setup] Setting up assist_pipeline
2025-05-17 07:12:36.952 INFO (MainThread) [homeassistant.setup] Setup of domain assist_pipeline took 0.00 seconds
2025-05-17 07:12:37.006 INFO (MainThread) [homeassistant.setup] Setting up bluetooth
2025-05-17 07:12:37.007 INFO (MainThread) [homeassistant.setup] Setup of domain bluetooth took 0.00 seconds
2025-05-17 07:12:37.009 INFO (MainThread) [homeassistant.setup] Setting up sensor
2025-05-17 07:12:37.009 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.00 seconds
2025-05-17 07:12:37.009 INFO (MainThread) [homeassistant.components.sensor] Setting up backup.sensor
2025-05-17 07:12:37.127 ERROR (ImportExecutor_0) [homeassistant.components.camera.img_util] Error loading libturbojpeg; Camera snapshot performance will be sub-optimal
Traceback (most recent call last):
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/components/camera/img_util.py", line 93, in __init__
    TurboJPEGSingleton.__instance = TurboJPEG()
                                    ~~~~~~~~~^^
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/turbojpeg.py", line 300, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/turbojpeg.py", line 967, in __find_turbojpeg
    raise RuntimeError(
    ...<2 lines>...
        'e.g. jpeg = TurboJPEG(lib_path)')
RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually.
e.g. jpeg = TurboJPEG(lib_path)
2025-05-17 07:12:37.164 INFO (MainThread) [homeassistant.setup] Setting up cloud
2025-05-17 07:12:37.166 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 0.00 seconds
2025-05-17 07:12:37.166 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'analytics', 'input_boolean', 'zone', 'sun', 'timer', 'input_text', 'counter', 'uk_bin_collection', 'tag', 'person', 'application_credentials', 'input_datetime', 'script', 'default_config', 'input_number', 'system_health', 'input_select', 'automation', 'scene', 'hardware', 'input_button', 'schedule'} | {'logger', 'network', 'frontend', 'backup'}
Dependencies: {'media_source', 'camera', 'my', 'go2rtc', 'mobile_app', 'homeassistant_alerts', 'history', 'blueprint', 'energy', 'image_upload', 'logbook', 'stream', 'trace'} | {'conversation', 'zeroconf', 'ffmpeg', 'usb', 'network', 'diagnostics', 'frontend', 'file_upload', 'tts', 'recorder', 'dhcp', 'search', 'backup', 'wake_word', 'assist_pipeline', 'config', 'stt', 'webhook', 'lovelace', 'ssdp', 'api', 'repairs', 'device_automation', 'bluetooth', 'onboarding', 'intent', 'cloud', 'system_log', 'http', 'auth', 'websocket_api'}
2025-05-17 07:12:37.166 INFO (MainThread) [homeassistant.setup] Setting up camera
2025-05-17 07:12:37.167 INFO (MainThread) [homeassistant.setup] Setup of domain camera took 0.00 seconds
2025-05-17 07:12:37.167 INFO (MainThread) [homeassistant.setup] Setting up scene
2025-05-17 07:12:37.167 INFO (MainThread) [homeassistant.setup] Setup of domain scene took 0.00 seconds
2025-05-17 07:12:37.167 INFO (MainThread) [homeassistant.setup] Setting up history
2025-05-17 07:12:37.167 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.00 seconds
2025-05-17 07:12:37.168 INFO (MainThread) [homeassistant.setup] Setting up input_boolean
2025-05-17 07:12:37.168 INFO (MainThread) [homeassistant.setup] Setup of domain input_boolean took 0.00 seconds
2025-05-17 07:12:37.168 INFO (MainThread) [homeassistant.setup] Setting up image_upload
2025-05-17 07:12:37.168 INFO (MainThread) [homeassistant.setup] Setup of domain image_upload took 0.00 seconds
2025-05-17 07:12:37.168 INFO (MainThread) [homeassistant.setup] Setting up person
2025-05-17 07:12:37.169 INFO (MainThread) [homeassistant.setup] Setting up blueprint
2025-05-17 07:12:37.169 INFO (MainThread) [homeassistant.setup] Setup of domain blueprint took 0.00 seconds
2025-05-17 07:12:37.169 INFO (MainThread) [homeassistant.setup] Setting up trace
2025-05-17 07:12:37.169 INFO (MainThread) [homeassistant.setup] Setup of domain trace took 0.00 seconds
2025-05-17 07:12:37.169 INFO (MainThread) [homeassistant.setup] Setting up script
2025-05-17 07:12:37.169 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.00 seconds
2025-05-17 07:12:37.169 INFO (MainThread) [homeassistant.setup] Setting up zone
2025-05-17 07:12:37.169 INFO (MainThread) [homeassistant.setup] Setup of domain zone took 0.00 seconds
2025-05-17 07:12:37.169 INFO (MainThread) [homeassistant.setup] Setting up logbook
2025-05-17 07:12:37.170 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 0.00 seconds
2025-05-17 07:12:37.170 INFO (MainThread) [homeassistant.setup] Setting up media_source
2025-05-17 07:12:37.170 INFO (MainThread) [homeassistant.setup] Setup of domain media_source took 0.00 seconds
2025-05-17 07:12:37.170 INFO (MainThread) [homeassistant.setup] Setting up stream
2025-05-17 07:12:37.170 INFO (MainThread) [homeassistant.setup] Setting up input_number
2025-05-17 07:12:37.171 INFO (MainThread) [homeassistant.setup] Setup of domain input_number took 0.00 seconds
2025-05-17 07:12:37.171 INFO (MainThread) [homeassistant.setup] Setting up timer
2025-05-17 07:12:37.171 INFO (MainThread) [homeassistant.setup] Setup of domain timer took 0.00 seconds
2025-05-17 07:12:37.171 INFO (MainThread) [homeassistant.setup] Setting up system_health
2025-05-17 07:12:37.171 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.00 seconds
2025-05-17 07:12:37.171 INFO (MainThread) [homeassistant.setup] Setting up input_select
2025-05-17 07:12:37.172 INFO (MainThread) [homeassistant.setup] Setup of domain input_select took 0.00 seconds
2025-05-17 07:12:37.172 INFO (MainThread) [homeassistant.setup] Setting up automation
2025-05-17 07:12:37.172 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.00 seconds
2025-05-17 07:12:37.172 INFO (MainThread) [homeassistant.setup] Setting up input_button
2025-05-17 07:12:37.172 INFO (MainThread) [homeassistant.setup] Setup of domain input_button took 0.00 seconds
2025-05-17 07:12:37.173 INFO (MainThread) [homeassistant.setup] Setup of domain person took 0.00 seconds
2025-05-17 07:12:37.174 INFO (MainThread) [homeassistant.components.scene] Setting up homeassistant.scene
2025-05-17 07:12:37.216 INFO (MainThread) [homeassistant.setup] Setting up energy
2025-05-17 07:12:37.216 INFO (MainThread) [homeassistant.setup] Setup of domain energy took 0.00 seconds
2025-05-17 07:12:37.225 INFO (MainThread) [homeassistant.setup] Setting up application_credentials
2025-05-17 07:12:37.225 INFO (MainThread) [homeassistant.setup] Setup of domain application_credentials took 0.00 seconds
2025-05-17 07:12:37.241 INFO (MainThread) [homeassistant.setup] Setting up input_datetime
2025-05-17 07:12:37.241 INFO (MainThread) [homeassistant.setup] Setup of domain input_datetime took 0.00 seconds
2025-05-17 07:12:37.292 INFO (MainThread) [homeassistant.setup] Setup of domain stream took 0.12 seconds
2025-05-17 07:12:37.304 INFO (MainThread) [homeassistant.setup] Setting up go2rtc
2025-05-17 07:12:37.304 INFO (MainThread) [homeassistant.setup] Setup of domain go2rtc took 0.00 seconds
2025-05-17 07:12:37.306 INFO (MainThread) [homeassistant.setup] Setting up homeassistant_alerts
2025-05-17 07:12:37.306 INFO (MainThread) [homeassistant.setup] Setup of domain homeassistant_alerts took 0.00 seconds
2025-05-17 07:12:37.309 INFO (MainThread) [homeassistant.setup] Setting up tag
2025-05-17 07:12:37.309 INFO (MainThread) [homeassistant.setup] Setup of domain tag took 0.00 seconds
2025-05-17 07:12:37.310 INFO (MainThread) [homeassistant.setup] Setting up my
2025-05-17 07:12:37.310 INFO (MainThread) [homeassistant.setup] Setup of domain my took 0.00 seconds
2025-05-17 07:12:37.311 INFO (MainThread) [homeassistant.setup] Setting up sun
2025-05-17 07:12:37.311 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.00 seconds
2025-05-17 07:12:37.312 INFO (MainThread) [homeassistant.components.sensor] Setting up sun.sensor
2025-05-17 07:12:37.313 INFO (MainThread) [homeassistant.setup] Setting up input_text
2025-05-17 07:12:37.314 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 0.00 seconds
2025-05-17 07:12:37.317 INFO (MainThread) [homeassistant.setup] Setting up counter
2025-05-17 07:12:37.317 INFO (MainThread) [homeassistant.setup] Setup of domain counter took 0.00 seconds
2025-05-17 07:12:37.736 ERROR (ImportExecutor_0) [homeassistant.loader] Unexpected exception importing platform custom_components.uk_bin_collection.config_flow
Traceback (most recent call last):
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1250, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1282, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidamor/GitHub/homeassistant-debug/config/custom_components/uk_bin_collection/config_flow.py", line 317
    This is commented out for now because configure is a headache to get working properly
                      ^^^
SyntaxError: invalid syntax
2025-05-17 07:12:37.737 INFO (MainThread) [homeassistant.setup] Setting up uk_bin_collection
2025-05-17 07:12:37.738 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection] async_setup called with config: {'default_config': {}, 'logger': {'default': 'info', 'logs': {'custom_components.uk_bin_collection': 'debug'}}, 'uk_bin_collection': []}
2025-05-17 07:12:37.738 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection] hass.data[DOMAIN] initialized: {}
2025-05-17 07:12:37.738 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection] Registering manual_refresh service
2025-05-17 07:12:37.738 DEBUG (MainThread) [custom_components.uk_bin_collection] [UKBinCollection] manual_refresh service registered successfully
2025-05-17 07:12:37.738 INFO (MainThread) [custom_components.uk_bin_collection] [UKBinCollection] async_setup completed without errors.
2025-05-17 07:12:37.738 INFO (MainThread) [homeassistant.setup] Setup of domain uk_bin_collection took 0.00 seconds
2025-05-17 07:12:37.740 INFO (MainThread) [homeassistant.setup] Setting up hardware
2025-05-17 07:12:37.744 INFO (MainThread) [homeassistant.setup] Setting up schedule
2025-05-17 07:12:37.745 INFO (MainThread) [homeassistant.setup] Setup of domain schedule took 0.00 seconds
2025-05-17 07:12:37.747 INFO (MainThread) [homeassistant.components.sensor] Setting up energy.sensor
2025-05-17 07:12:37.756 INFO (MainThread) [homeassistant.setup] Setup of domain hardware took 0.02 seconds
2025-05-17 07:12:37.757 INFO (MainThread) [homeassistant.setup] Setting up analytics
2025-05-17 07:12:37.757 INFO (MainThread) [homeassistant.setup] Setup of domain analytics took 0.00 seconds
2025-05-17 07:12:37.774 INFO (MainThread) [homeassistant.setup] Setting up mobile_app
2025-05-17 07:12:37.775 INFO (MainThread) [homeassistant.setup] Setting up notify
2025-05-17 07:12:37.775 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 0.00 seconds
2025-05-17 07:12:37.775 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 0.00 seconds
2025-05-17 07:12:37.775 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2025-05-17 07:12:37.775 INFO (MainThread) [homeassistant.setup] Setting up default_config
2025-05-17 07:12:37.775 INFO (MainThread) [homeassistant.setup] Setup of domain default_config took 0.00 seconds
2025-05-17 07:12:37.778 ERROR (ImportExecutor_0) [homeassistant.loader] Unexpected exception importing platform custom_components.uk_bin_collection.config_flow
Traceback (most recent call last):
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1250, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1282, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidamor/GitHub/homeassistant-debug/config/custom_components/uk_bin_collection/config_flow.py", line 317
    This is commented out for now because configure is a headache to get working properly
                      ^^^
SyntaxError: invalid syntax
2025-05-17 07:12:37.781 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.uk_bin_collection.config_flow',) in /Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py, line 1282: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/davidamor/.vscode/extensions/ms-python.debugpy-2025.8.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/Users/davidamor/.vscode/extensions/ms-python.debugpy-2025.8.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/Users/davidamor/.vscode/extensions/ms-python.debugpy-2025.8.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 384, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/Users/davidamor/.vscode/extensions/ms-python.debugpy-2025.8.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 228, in _run_module_as_main
    return _run_code(code, main_globals, None, "__main__", mod_spec)
  File "/Users/davidamor/.vscode/extensions/ms-python.debugpy-2025.8.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 706, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 677, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 2034, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/config_entries.py", line 894, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/config_entries.py", line 660, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/config_entries.py", line 716, in __async_setup_with_context
    await integration.async_get_platform("config_flow")
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1086, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1151, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1076, in _load_platforms
    platform_name: self._load_platform(platform_name)
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1250, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1282, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")

2025-05-17 07:12:37.782 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.uk_bin_collection.config_flow
Traceback (most recent call last):
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1250, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1282, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidamor/GitHub/homeassistant-debug/.venv/lib/python3.13/site-packages/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/davidamor/GitHub/homeassistant-debug/config/custom_components/uk_bin_collection/config_flow.py", line 317
    This is commented out for now because configure is a headache to get working properly
                      ^^^
SyntaxError: invalid syntax
2025-05-17 07:12:37.783 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration uk_bin_collection to set up uk_bin_collection configuration entry: Exception importing custom_components.uk_bin_collection.config_flow
2025-05-17 07:12:37.783 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration uk_bin_collection to set up uk_bin_collection configuration entry: Exception importing custom_components.uk_bin_collection.config_flow
2025-05-17 07:12:37.783 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration uk_bin_collection to set up uk_bin_collection configuration entry: Exception importing custom_components.uk_bin_collection.config_flow
2025-05-17 07:12:37.783 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration uk_bin_collection to set up uk_bin_collection configuration entry: Exception importing custom_components.uk_bin_collection.config_flow
2025-05-17 07:12:37.783 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration uk_bin_collection to set up uk_bin_collection configuration entry: Exception importing custom_components.uk_bin_collection.config_flow
2025-05-17 07:12:37.783 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration uk_bin_collection to set up uk_bin_collection configuration entry: Exception importing custom_components.uk_bin_collection.config_flow
2025-05-17 07:12:37.783 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration uk_bin_collection to set up uk_bin_collection configuration entry: Exception importing custom_components.uk_bin_collection.config_flow
2025-05-17 07:12:37.783 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration uk_bin_collection to set up uk_bin_collection configuration entry: Exception importing custom_components.uk_bin_collection.config_flow
2025-05-17 07:12:37.783 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration uk_bin_collection to set up uk_bin_collection configuration entry: Exception importing custom_components.uk_bin_collection.config_flow
2025-05-17 07:12:37.783 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration uk_bin_collection to set up uk_bin_collection configuration entry: Exception importing custom_components.uk_bin_collection.config_flow
2025-05-17 07:12:37.783 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 1.48s
2025-05-17 07:12:37.784 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2025-05-17 07:12:37.861 INFO (SyncWorker_0) [homeassistant.loader] Loaded androidtv_remote from homeassistant.components.androidtv_remote
2025-05-17 07:12:37.862 INFO (SyncWorker_2) [homeassistant.loader] Loaded sonos from homeassistant.components.sonos
2025-05-17 07:12:37.862 INFO (SyncWorker_3) [homeassistant.loader] Loaded synology_dsm from homeassistant.components.synology_dsm
2025-05-17 07:12:37.937 INFO (SyncWorker_1) [homeassistant.loader] Loaded apple_tv from homeassistant.components.apple_tv
2025-05-17 07:12:38.179 INFO (SyncWorker_3) [homeassistant.loader] Loaded cast from homeassistant.components.cast
2025-05-17 07:12:38.179 INFO (SyncWorker_5) [homeassistant.loader] Loaded spotify from homeassistant.components.spotify
2025-05-17 07:12:38.184 INFO (SyncWorker_4) [homeassistant.loader] Loaded brother from homeassistant.components.brother
2025-05-17 07:12:38.184 INFO (SyncWorker_1) [homeassistant.loader] Loaded ipp from homeassistant.components.ipp
2025-05-17 07:12:38.203 INFO (SyncWorker_6) [homeassistant.loader] Loaded thread from homeassistant.components.thread
2025-05-17 07:12:49.035 INFO (SyncWorker_1) [homeassistant.loader] Loaded nest from homeassistant.components.nest
2025-05-17 07:12:49.036 INFO (SyncWorker_4) [homeassistant.loader] Loaded tuya from homeassistant.components.tuya
2025-05-17 07:12:49.036 INFO (SyncWorker_5) [homeassistant.loader] Loaded unifiprotect from homeassistant.components.unifiprotect
